version: '3.3'

services:
  postgresdb_1:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
    networks:
      -  user-acc-mgmt-serv_mynetwork

  app:
    depends_on:
      - postgresdb_1
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DATABASE
      - DB_PORT=$POSTGRES_DOCKER_PORT
      - PRISMA_MIGRATE_TIMEOUT=30000
    stdin_open: true
    tty: true
    networks:
      -  user-acc-mgmt-serv_mynetwork

volumes:
  db:
networks:
   user-acc-mgmt-serv_mynetwork:
    external: true
